Hw 2
SherAndrei/Sphere pull request #3
Opened 2020-10-25 10:30 UTC by SherAndrei

Запоздалое домашнее задание номер 2!

2020-10-30 08:11 UTC, Kapitonov requested changes

2020-10-30 08:11 UTC, Kapitonov commented on 2.LOG/lib/baselogger.cpp
> +    flush();
Наскольку помню, по стандарту, члены класса наследника уничтожаются раньше чем вызывается дестструктор предка, тогда ваш out_ будет указывать на нусуществуюший объект, что может привести к segmentation fault.

2020-10-30 08:11 UTC, Kapitonov commented on 2.LOG/lib/filelogger.cpp
> +    file.close();
Тут деструктор std::ofstream сам все сделает.

2020-10-30 08:39 UTC, SherAndrei commented on 2.LOG/lib/baselogger.cpp
> +    flush();
Да, вы правы.

2020-11-03 16:04 UTC, Kapitonov requested changes

2020-11-03 16:04 UTC, Kapitonov commented on 2.LOG/include/baselogger.h
> +    std::shared_ptr<std::ostream> _out;
А что произодет, если мы попробуем удалить std::cout? Кажется, что здесь лучше или обычный указатель или ссылка. Ну или удалить, файл который уже удалил дескриптор FileLogger.

2020-11-03 16:04 UTC, Kapitonov commented on 2.LOG/lib/baselogger.cpp
> +void  BaseLogger::debug(const std::string& message) { log("[DEBUG]: "   + message, LEVEL::DEBUG); }
Такой стиль иногда употребляют в заголовочных файлах, в cpp не уверен, что он уместен.

2020-11-03 16:04 UTC, Kapitonov commented on 2.LOG/lib/globallogger.cpp
> +    lg.set_global_logger(std::move(pbl));
Тут лучше использовать make_unique, он сразу создаст временный объект.

2020-11-03 16:04 UTC, Kapitonov commented on 2.LOG/lib/globallogger.cpp
> +    Logger& lg = Logger::get_instance();
А почему не объеденить данные строчки в одну, не думаю что потеряется читаемость.

2020-11-11 19:46 UTC, Kapitonov requested changes

2020-11-11 19:46 UTC, Kapitonov commented on 2.LOG/lib/filelogger.cpp
> +    : log::BaseLogger(file, l), file(path) {
Сначала инициализируются члены класса, затем вызывается конструктор базового класса.

2020-11-11 19:46 UTC, Kapitonov commented on 2.LOG/lib/logger.cpp
> +        global_loger_->flush();
flush сделают деструкторы объектов.

2020-11-11 19:46 UTC, Kapitonov commented on 2.LOG/include/level.h
> +    BASE = -1,
Не вижу по коду разницы от DEBUG

2020-11-17 21:45 UTC, merged