Hw 4
SherAndrei/Sphere pull request #4
Opened 2020-10-29 18:31 UTC by SherAndrei

Домашнее задание номер 4!

2020-11-11 23:22 UTC, Kapitonov requested changes

2020-11-11 23:22 UTC, Kapitonov commented on 4.SharedMap/include/shmap.h
> +    auto begin() {
А это точно удачная затея отдавать указатели на объекты?

2020-11-11 23:22 UTC, Kapitonov commented on 4.SharedMap/include/shmap.h
> +    auto& operator[](const Key& k) {
Что произойдет, если какой-то поток удалит объект ссылку на который вы вернули?

2020-11-12 23:37 UTC, SherAndrei commented on 4.SharedMap/include/shmap.h
> +    auto& operator[](const Key& k) {
Ого, не подумал

2020-11-20 17:51 UTC, Kapitonov requested changes

2020-11-20 17:51 UTC, Kapitonov commented on 4.SharedMap/include/shmap.h
> +    }
Добавить пустые строки по аналогии с остальным кодом.

2020-11-26 11:28 UTC, Kapitonov requested changes
Поправьте отступы и сливайте.

2020-11-26 11:28 UTC, Kapitonov commented on 4.SharedMap/include/shmap.h
> +class SharedMap {
Поехали отступы в классе.

2020-11-26 12:43 UTC, merged