Hw 5
SherAndrei/Sphere pull request #5
Opened 2020-11-06 13:25 UTC by SherAndrei

Домашнее задание номер 5!

2020-11-06 16:21 UTC, a-badin requested changes

2020-11-06 16:21 UTC, a-badin commented on 5.Service/include/epoll.h
> +    static const int MAX_EVENTS = 1000;
в реализацию

2020-11-06 16:21 UTC, a-badin commented on 5.Service/include/epoll.h
> +    void wait(int timeout);
max_events, или setter

2020-11-06 16:21 UTC, a-badin commented on 5.Service/include/service.h
> +    explicit Service(std::shared_ptr<IServiceListener> listener);
или weak или raw

2020-11-12 15:17 UTC, a-badin requested changes
Перейдите уже в плоскость работы с char
Логика вызова ::read и ::write должна быть на стороне Service
В колбеках пользователь роботает только с буферами соединения.
Service append'ит данные в конец буфера при чтении и дергает колбек.
Service пишет данные из буфера при записи и дергает колбек, когда буфер стал пустым.
Продумайте возможность закрыть соединение из колбека

2020-11-12 15:17 UTC, a-badin commented on 5.Service/lib/epoll.cpp
> +    handle_error(events_count = ::epoll_wait(epoll_fd_.fd(),
Разбейте по строкам, отдельно epoll_wait, отдельно обработка ошибки

2020-11-12 15:17 UTC, a-badin commented on 5.Service/lib/epoll.cpp
> +    return { event_queue.begin(), event_queue.begin() + events_count };
Зачем вам держать в классе event_queue? Вы ведь заполняете его здесь и стразу отдаете. Так бы сработал RVO и вектор не копировался бы

2020-11-12 15:17 UTC, a-badin commented on 5.Service/include/bufconnection.h
> +    void* data();
Не очень удобно, можно выйти за пределы буфера.
Могли оставить просто строку

2020-11-12 15:17 UTC, a-badin commented on 5.Service/include/bufconnection.h
> +    Buffer read_  = Buffer{512};
Buffer read_{512}

2020-11-12 15:17 UTC, a-badin commented on 5.Service/include/epoll.h
> +    void mod(const tcp::Descriptor& fd);
Что-то не понятно, а параметр option где?
То есть сначала нужно его выставить через set_option а потом "применить" через mod?
Чем больше у вас состояний у классов, тем проще наделать в них ошибок. Чем меньше флажков и других членов данных - тем лучше

2020-11-12 15:17 UTC, a-badin commented on 5.Service/lib/epoll.cpp
> +    event.events  = static_cast<uint32_t>(_opt) | EPOLLRDHUP;
Передайте лучше opt_ параметром у метода

2020-11-12 15:17 UTC, a-badin commented on 5.Service/lib/epoll.cpp
> +    handle_error(epoll_ctl(epoll_fd_.fd(), EPOLL_CTL_ADD,
Разделите вызов метода и обработку ошибки

2020-11-12 15:17 UTC, a-badin commented on 5.Service/lib/epoll.cpp
> +    handle_error(epoll_ctl(epoll_fd_.fd(), EPOLL_CTL_DEL,
читайте man, для DEL event может быть nullptr, так как он игнорируется

2020-11-12 15:17 UTC, a-badin commented on 5.Service/lib/service.cpp
> +    , server_()
дефолтные конструкторы вызываются сами

2020-11-12 15:17 UTC, a-badin commented on 5.Service/lib/service.cpp
> +    epoll_.del(bc->fd());
epoll сам вычищает закрытые дескрипторы

2020-11-12 15:17 UTC, a-badin commented on 5.Service/lib/service.cpp
> +static auto find_client_it(std::list<net::BufferedConnection>* list, int fd) {
Почему лист передается по указателю?

2020-11-12 15:17 UTC, a-badin commented on 5.Service/lib/service.cpp
> +void net::Service::setListener(IServiceListener* listener) {
Вместо того чтобы везде приписывать net:: поместите все определения функций в блок namespace net

2020-11-12 15:17 UTC, a-badin commented on 5.Service/lib/service.cpp
> +        epoll_events = epoll_.wait();
Лучше сразу тут и объявить вектор

2020-11-12 15:17 UTC, a-badin commented on 5.Service/lib/service.cpp
> +        for (auto it = epoll_events.begin(); it != epoll_events.end(); it++) {
`for (::epoll_event& event : epoll_events) {`

2020-11-12 15:17 UTC, a-badin commented on 5.Service/tests/calculator.cpp
> +    void onNewConnection(net::BufferedConnection* cn) override {
Почему по указателю?

2020-11-12 15:17 UTC, a-badin commented on 5.Service/lib/service.cpp
> +                auto& client = *it_client;
Лучше не пользоваться auto

2020-11-12 15:17 UTC, a-badin commented on 5.Service/lib/service.cpp
> +                if (client.read_buf().empty())
А если не пуст - зациклимся?

2020-11-12 15:17 UTC, a-badin commented on 5.Service/tests/test.cpp
> +        cn->read(buf.data(), buf.length());
Вот эту логику нужно перенести в Service - шанс того что при получении события onReadAvailable пользователь НЕ станет читать в буфер крайне мал

2020-11-12 15:17 UTC, a-badin commented on 5.Service/lib/service.cpp
> +                listener_->onWriteDone(&client);
Но мы же ничего не писали, вызывать onWriteDone нужно когда вы смогли записать весь буфер внутри BufferedConnection

2020-11-12 15:17 UTC, a-badin commented on 5.Service/lib/bufconnection.cpp
> +    p_epoll_->set_option(add(p_epoll_->option(), opt));
Состояния у вас у соединений могут быть разные, а вы используйте одно на всех в Epoll
Вам тогда нужно заводить состояние в BufferedConnection

2020-11-12 15:19 UTC, a-badin requested changes

2020-11-12 15:19 UTC, a-badin commented on 5.Service/lib/service.cpp
> +    bc->close();
Чтобы вызывать close у BufferedConnection не нужно "прокидывать" его в Service. Ведь вам никто не мешает дернуть close выше этой функции.
Вам нужно как-то вычистить BufferedConnection из вашего списка connections_ - вот это уже интереснее

2020-11-12 20:58 UTC, SherAndrei commented on 5.Service/lib/service.cpp
> +static auto find_client_it(std::list<net::BufferedConnection>* list, int fd) {
Потому что если передавать по константной ссылке, то будет возвращаться константный итератор.
Можно, конечно, передавать не по константной. Лучше сделать таким образом? И если да, то почему?

2020-11-12 21:36 UTC, SherAndrei commented on 5.Service/tests/calculator.cpp
> +    void onNewConnection(net::BufferedConnection* cn) override {
Аналогично листу в функции find_client_it()
Сюда можно еще передавать rvalue ref, но тогда мы же будем терять соединение, и чтобы с ним работать дальше, надо делать какую-то сложную логику. Надо как-то показать, что пользователь как бы владеет, но как бы нет соединением, поэтому выбрал ссылку.

2020-11-13 16:34 UTC, a-badin commented on 5.Service/lib/service.cpp
> +                    if (client.is_open()) {
is_close вернуться из epoll не может

2020-11-13 16:34 UTC, a-badin commented on 5.Service/lib/service.cpp
> +static auto find_client_it(std::list<net::BufferedConnection>* list, int fd) {
Остается

2020-11-13 16:41 UTC, a-badin requested changes

2020-11-13 16:41 UTC, a-badin commented on 5.Service/lib/service.cpp
> +                    connections_.erase(it_client);
Поменять, например, в случае если пользователь отписался от всего

2020-11-19 09:18 UTC, a-badin approved these changes

2020-11-19 09:18 UTC, a-badin commented on 5.Service/tests/calculator.cpp
> +        cn.subscribe(net::OPTION::READ_AND_WRITE);
нет смысла подписываться на write с пустым буфером на запись - вы просто в холостую отрабатываете onWriteDone

2020-11-19 09:18 UTC, a-badin commented on 5.Service/tests/CMakeLists.txt
> +set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
вот это вам не даст иметь и релизную и дебажную сборку одновременно, практику out-of-source build

2020-11-19 09:18 UTC, a-badin commented on 5.Service/tests/calculator.cpp
> +        cn.write(&(result), sizeof(int));
Вот когда вам стало что писать - тогда вы подписываетесь на write

2020-11-19 09:18 UTC, a-badin commented on 5.Service/lib/bufconnection.cpp
> +    std::copy(read_.data(), read_.data() + len, ch_d);
если в read_ меньше данных чем len вы получите segfault

2020-11-19 09:18 UTC, a-badin commented on 5.Service/lib/bufconnection.cpp
> +    const std::string to_app = {ch_d, ch_d + std::min(available_size(), len)};
Я вас прошу перестаньте заниматься байтослесарством, пользутесь std::string

2020-11-19 09:20 UTC, a-badin commented
Засчитываю на 14, правьте конфликты и сливайте ветку.

2020-11-23 18:57 UTC, a-badin commented on 5.Service/tests/calculator.cpp
> +            for (int i = 0; i < 2; i++)
У вас уже скопированы данные, можно не копировать их ещё раз
```
int* numbers = reinterpret_cast<int*>(buffer.data());
int sum = numbers[0] + numbers[1];
```

2020-11-23 18:58 UTC, merged