Hw 6
SherAndrei/Sphere pull request #6
Opened 2020-11-20 14:28 UTC by SherAndrei

Домашнее задание номер 6!

2020-11-27 16:08 UTC, Kapitonov requested changes
Нет keep-alive.

2020-11-27 16:08 UTC, Kapitonov commented on 5.Service/include/bufconnection.h
> +class BufferedConnection : public tcp::Connection {
Скорее не public, а protected.

2020-11-27 16:08 UTC, Kapitonov commented on 6.HTTP/include/httpservice.h
> +    void setWorkersSize(size_t size);
А вы сможете изменить количество воркеров во время работы?

2020-11-27 16:08 UTC, Kapitonov commented on 6.HTTP/lib/httpservice.cpp
> +        tcp::Connection new_c = server_.accept();
Блокировка на неопределнное время. Хотя у вас есть код, котрый надо регулярно выполнять.

2020-11-27 16:08 UTC, Kapitonov commented on 6.HTTP/lib/message.cpp
> +template<class InputIt1, class InputIt2>
Зачем шаблонность?

2020-11-27 16:08 UTC, Kapitonov commented on 6.HTTP/lib/worker.cpp
> +                p_client->subscribe(net::OPTION::WRITE);
Проверить добавление дополднитеольеых флагов(EPOLLONESHOT)

2020-12-04 16:59 UTC, Kapitonov requested changes

2020-12-04 16:59 UTC, Kapitonov commented on 2.LOG/lib/baselogger.cpp
> +    std::scoped_lock sl(mutex_);
А не проще тогда в функции log брать мьютекс?

2020-12-04 16:59 UTC, Kapitonov commented on 5.Service/lib/bufconnection.cpp
> +    epoll_option_ = epoll_option_ + opt + net::OPTION::CLOSE;
А где теперь дергаем epoll?

2020-12-04 16:59 UTC, Kapitonov commented on 6.HTTP/include/message.h
> +    std::vector<Header> headers() const;
map?

2020-12-04 16:59 UTC, Kapitonov commented on 6.HTTP/lib/httpservice.cpp
> +for(;;) {                              \
дальше вы использовали while(true), может здесь тоже его использовать?

2020-12-04 16:59 UTC, Kapitonov commented on 6.HTTP/lib/httpservice.cpp
> +        mutex_.lock_shared();
не лучше ли будет ?

{
  std::shared_lock lock(mutex);
  bool closed_non_empty = !closed_.empty();
}

2020-12-04 16:59 UTC, Kapitonov commented on 6.HTTP/lib/httpservice.cpp
> +    cn.epoll_option_ = cn.epoll_option_ + opt + net::OPTION::ET_ONESHOT;
А точно +, а не битовые операции?

2020-12-04 16:59 UTC, Kapitonov commented on 6.HTTP/lib/httpservice.cpp
> +    cn.epoll_option_ = cn.epoll_option_ - opt + net::OPTION::ET_ONESHOT;
Аналгично.

2020-12-04 16:59 UTC, Kapitonov commented on 6.HTTP/lib/message.cpp
> +    auto it = std::find_if(headers.begin(), headers.end(), [] (const http::Header& h) {
А если нет данного параметра в заголовке, то мы не будем работать с такими запросами?

2020-12-04 16:59 UTC, Kapitonov commented on 6.HTTP/lib/message.cpp
> +    body_    = parse_body(headers_, req_sv);
Лишние пробелы?

2020-12-04 16:59 UTC, Kapitonov commented on 6.HTTP/tests/stress.sh
> +    gnome-terminal --command $client
А если у меня нет такого терминала?

Лучше
./client &
./client &

2020-12-04 16:59 UTC, Kapitonov commented on 6.HTTP/lib/httpservice.cpp
> +                close_if_timed_out(&connection);
Я правильно понимаю, что если нам будут постоянно приходить сооединения, то мы не будем проверять старые на протухание?

2020-12-04 16:59 UTC, Kapitonov commented on 6.HTTP/include/timeout.h
> +inline constexpr int KEEP_ALIVE_CONNECTION_TIMEOUT = 60;
А мы не хоти уметь настраивать данные параметры у сервера, кажется что жестко их прибивать не самая лучшая идея.

2020-12-04 17:24 UTC, SherAndrei commented on 6.HTTP/lib/httpservice.cpp
> +                close_if_timed_out(&connection);
Не будут проверяться только keep-alive соединения, но я над этим еще попробую подумать!

2020-12-04 17:27 UTC, SherAndrei commented on 6.HTTP/lib/httpservice.cpp
> +    cn.epoll_option_ = cn.epoll_option_ + opt + net::OPTION::ET_ONESHOT;
Эти операции переопределены для OPTION в option.cpp :^)

2020-12-04 17:37 UTC, SherAndrei commented on 5.Service/lib/bufconnection.cpp
> +    epoll_option_ = epoll_option_ + opt + net::OPTION::CLOSE;
в service.cpp на 76 строчке

2020-12-04 18:01 UTC, a-badin commented on 6.HTTP/lib/httpservice.cpp
> +    std::lock_guard<std::mutex> lock(mutex_);
лок в каждое соединение

2020-12-04 18:01 UTC, a-badin commented on 6.HTTP/include/httpservice.h
> +    PtrsToClosedHttpConnections closed_;
struct ??? {Connection*, iterator};
std::list<???> timeouting_queue_;
std::mutex eще_один

2020-12-08 15:41 UTC, Kapitonov requested changes

2020-12-08 15:41 UTC, Kapitonov commented on 7.Coroutines/tests/lecture/man.cpp
> +#include <ucontext.h>
А это точно про 6 домашку?

2020-12-08 15:48 UTC, merged